### ISSUE TITLE
XP/Leveling

### ISSUE THREAD

**Issue by ConnorMc27** [ConnorMc27/LifestyleRPG#3]
NextLevelXP = PREVIOUS Level Xp + PREVIOUS Level Xp * 10%
NextLevelXP = Exp * Exp / 100

**Comment by MurrayInAHurry** [comment]
Public Class Form1
    Dim level As Single
    Dim Ex As Integer = 0
    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) _
                 Handles Button1.Click
        '--------------------------------------------------------------
        '---------------(old code)-------------------------------------
        '--------------------------------------------------------------
        'increment = increment + 10
        'If increment > ProgressBar1.Maximum Then
        'increment = ProgressBar1.Maximum
        'End If
        '
        'ProgressBar1.Value = increment
        'If ProgressBar1.Value = 100 Then
        'increment = 0
        '
        'End If
        '--------------------------------------------------------------



        ProgressBar1.Maximum = level * 10

        Ex = Ex + 10
        If Ex > ProgressBar1.Maximum Then
            Ex = ProgressBar1.Maximum
        End If

        If ProgressBar1.Value = level * 10 Then
            Ex = 0

            lblLevel.Text = level
            level = level + 1

        End If

        ProgressBar1.Value = Ex

    End Sub
End Class

**Comment by MurrayInAHurry** [comment]
Public Class Form1
    Dim level As Integer = 1
    Dim Ex As Integer = 0
    Dim number As Integer

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) _
    Handles Button1.Click
        '--------------------------------------------------------------
        '---------------(old code)-------------------------------------
        '--------------------------------------------------------------
        'increment = increment + 10
        'If increment > ProgressBar1.Maximum Then
        'increment = ProgressBar1.Maximum
        'End If
        '
        'ProgressBar1.Value = increment
        'If ProgressBar1.Value = 100 Then
        'increment = 0
        '
        'End If
        '--------------------------------------------------------------

        ProgressBar1.Maximum = level * 10
        lblNum.Text = number
        number = ProgressBar1.Maximum

        Ex = Ex + 5
        If Ex > ProgressBar1.Maximum Then
            Ex = ProgressBar1.Maximum

        End If


        If ProgressBar1.Value = level * 10 Then
            Ex = 0

            level = level + 1
            lblLevel.Text = level


        End If

        ProgressBar1.Value = Ex

    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        lblLevel.Text = 1

    End Sub
End Class

**Comment by MurrayInAHurry** [comment]
Public Class Form1
    Dim level As Integer
    Dim Ex As Integer = 0
    Dim number As Integer
    Dim count As String
    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) _
    Handles Button1.Click
        '--------------------------------------------------------------
        '---------------(old code)-------------------------------------
        '--------------------------------------------------------------
        'increment = increment + 10
        'If increment > ProgressBar1.Maximum Then
        'increment = ProgressBar1.Maximum
        'End If
        '
        'ProgressBar1.Value = increment
        'If ProgressBar1.Value = 100 Then
        'increment = 0
        '
        'End If
        '--------------------------------------------------------------

        ProgressBar1.Maximum = level * 10


        Ex = Ex + 5
        If Ex > ProgressBar1.Maximum Then
            Ex = ProgressBar1.Maximum

        End If

        ProgressBar1.Value = Ex

        If ProgressBar1.Value = level * 10 Then
            Ex = 0

            level = level + 1
            lblLevel.Text = level


        End If

        ProgressBar1.Value = Ex

        lblEx.Text = count

        lblEx.Text = ProgressBar1.Value & "/" & ProgressBar1.Maximum


    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        lblLevel.Text = 1
    End Sub
End Class

**Comment by MurrayInAHurry** [comment]
(Full code with buttons)

Public Class Form1
    Dim level As Integer
    Dim Ex As Integer = 0
    Dim number As Integer
    Dim count As String
    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) _
    Handles Button1.Click
        '--------------------------------------------------------------
        '---------------(old code)-------------------------------------
        '--------------------------------------------------------------
        'increment = increment + 10
        'If increment > ProgressBar1.Maximum Then
        'increment = ProgressBar1.Maximum
        'End If
        '
        'ProgressBar1.Value = increment
        'If ProgressBar1.Value = 100 Then
        'increment = 0
        '
        'End If
        '--------------------------------------------------------------

        ProgressBar1.Maximum = level * 10


        Ex = Ex + 5
        If Ex > ProgressBar1.Maximum Then
            Ex = ProgressBar1.Maximum

        End If

        ProgressBar1.Value = Ex

        If ProgressBar1.Value = level * 10 Then
            Ex = 0

            level = level + 1
            lblLevel.Text = level


        End If

        ProgressBar1.Value = Ex



        '--------------------------------------------------------------
        lblEx.Text = count

        lblEx.Text = ProgressBar1.Value & "/" & ProgressBar1.Maximum
        '--------------------------------------------------------------


    End Sub
    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click

        '--------------------------------------------------------------

        ProgressBar1.Maximum = level * 10


        Ex = Ex + 5
        If Ex > ProgressBar1.Maximum Then
            Ex = ProgressBar1.Maximum

        End If

        ProgressBar1.Value = Ex

        If ProgressBar1.Value = level * 10 Then
            Ex = 0

            level = level + 1
            lblLevel.Text = level


        End If

        ProgressBar1.Value = Ex



        '--------------------------------------------------------------
        lblEx.Text = count

        lblEx.Text = ProgressBar1.Value & "/" & ProgressBar1.Maximum
        '--------------------------------------------------------------


    End Sub

    Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click

        '--------------------------------------------------------------

        ProgressBar1.Maximum = level * 10


        Ex = Ex + 5
        If Ex > ProgressBar1.Maximum Then
            Ex = ProgressBar1.Maximum

        End If

        ProgressBar1.Value = Ex

        If ProgressBar1.Value = level * 10 Then
            Ex = 0

            level = level + 1
            lblLevel.Text = level


        End If

        ProgressBar1.Value = Ex



        '--------------------------------------------------------------
        lblEx.Text = count

        lblEx.Text = ProgressBar1.Value & "/" & ProgressBar1.Maximum
        '--------------------------------------------------------------


    End Sub
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        lblLevel.Text = 1
    End Sub
End Class
