### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by MurrayInAHurry** [ConnorMc27/LifestyleRPG#7]
Can get different coloured backgrounds and effects form leveling up

**Comment by ConnorMc27** [comment]
Currency is not purchasable. you earn it as a reward for doing set tasks.The amount you get rewarded is dependent on the difficulty, the time taken to complete the task, and your level range

**Comment by MurrayInAHurry** [comment]
Item quality in shop

Common (can be earned for levelling)
- backgrounds (one colour e.g. red, blue...)
- button

Uncommon (shop)
- Effects
- backgrounds (custom)

Rare (shop)
- Effect (custom)

**Comment by MurrayInAHurry** [comment]
**Shop**
Common items: 5-10 coins
1.	Blue background
2.	Red Background
3.	Green background
4.	Yellow background
5.	Blue button
6.	Red button
7.	Green button
8.	Yellow button

Uncommon items: 15-20 coins
1.	Snow effect
2.	Rain effect
3.	Flowers effect
